package com.goctrithuc.backend.services;

import com.goctrithuc.backend.common.util.StringUtil;
import com.goctrithuc.backend.entities.User;
import com.goctrithuc.backend.entities.UserProvider;
import com.goctrithuc.backend.repositories.UserProviderRepository;
import com.goctrithuc.backend.repositories.UserRepository;
import jakarta.transaction.Transactional;
import java.util.Optional;
import org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService;
import org.springframework.security.oauth2.client.userinfo.OAuth2UserRequest;
import org.springframework.security.oauth2.core.OAuth2AuthenticationException;
import org.springframework.security.oauth2.core.user.OAuth2User;
import org.springframework.stereotype.Service;

@Service
public class CustomOAuth2UserService extends DefaultOAuth2UserService {

  private final UserRepository userRepository;
  private final UserProviderRepository userProviderRepository;

  public CustomOAuth2UserService(
      UserRepository userRepository, UserProviderRepository userProviderRepository) {
    this.userRepository = userRepository;
    this.userProviderRepository = userProviderRepository;
  }

  @Override
  @Transactional
  public OAuth2User loadUser(OAuth2UserRequest userRequest) throws OAuth2AuthenticationException {
    // Load user info from the provider (e.g., Google)
    OAuth2User oAuth2User = super.loadUser(userRequest);

    String providerName = userRequest.getClientRegistration().getRegistrationId(); // e.g., "google"
    String providerUserId = oAuth2User.getAttribute("sub"); // Google's unique ID for the user
    String email = oAuth2User.getAttribute("email");
    String name = oAuth2User.getAttribute("name");
    String avatar = oAuth2User.getAttribute("picture");

    // Check if this specific account is already in our DB
    Optional<UserProvider> existingProvider =
        userProviderRepository.findByProviderNameAndProviderUserId(providerName, providerUserId);

    if (existingProvider.isEmpty()) {
      // Brand new login! Check if the email exists from another provider
      User user =
          userRepository
              .findByEmail(email)
              .orElseGet(() -> createUserWithUniqueUsername(email, name, avatar));

      // 4. Link this Google account to the User
      UserProvider newProvider = new UserProvider(user, providerName, providerUserId);
      userProviderRepository.save(newProvider);
    }

    return oAuth2User;
  }

  private User createUserWithUniqueUsername(String email, String name, String avatar) {
    int maxAttempts = 5;

    for (int i = 0; i < maxAttempts; i++) {
      String autogeneratedUsername = StringUtil.generateBaseSuffixUsername(name);

      if (!userRepository.existsByUsername(autogeneratedUsername)) {
        User newUser = new User(email, name, autogeneratedUsername, avatar);
        return userRepository.save(newUser);
      }
    }

    throw new RuntimeException(
        "Could not generate a unique username after " + maxAttempts + " attempts");
  }
}
