package com.goctrithuc.backend.services;

import com.goctrithuc.backend.common.PermissionConstants;
import com.goctrithuc.backend.common.RoleConstants;
import com.goctrithuc.backend.common.util.StringUtil;
import com.goctrithuc.backend.dtos.UpdateUserRequest;
import com.goctrithuc.backend.entities.Role;
import com.goctrithuc.backend.entities.User;
import com.goctrithuc.backend.entities.UserProvider;
import com.goctrithuc.backend.entities.UserRole;
import com.goctrithuc.backend.repositories.RoleRepository;
import com.goctrithuc.backend.repositories.UserProviderRepository;
import com.goctrithuc.backend.repositories.UserRepository;
import com.goctrithuc.backend.repositories.UserRoleRepository;
import java.util.Optional;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class UserPersistenceService {

  private static final String DEFAULT_ROLE_NAME = RoleConstants.STUDENT;

  private final UserRepository userRepository;
  private final UserProviderRepository userProviderRepository;
  private final RoleRepository roleRepository;
  private final UserRoleRepository userRoleRepository;

  public UserPersistenceService(
      UserRepository userRepository,
      UserProviderRepository userProviderRepository,
      RoleRepository roleRepository,
      UserRoleRepository userRoleRepository) {
    this.userRepository = userRepository;
    this.userProviderRepository = userProviderRepository;
    this.roleRepository = roleRepository;
    this.userRoleRepository = userRoleRepository;
  }

  @Transactional
  public void syncUser(
      String providerName, String providerUserId, String email, String name, String avatar) {
    Optional<UserProvider> existingProvider =
        userProviderRepository.findByProviderNameAndProviderUserId(providerName, providerUserId);

    if (existingProvider.isEmpty()) {
      User user =
          userRepository
              .findByEmail(email)
              .orElseGet(() -> createUserWithUniqueUsername(email, name, avatar));

      UserProvider newProvider = new UserProvider(user, providerName, providerUserId);
      userProviderRepository.save(newProvider);
    }
  }

  private User createUserWithUniqueUsername(String email, String name, String avatar) {
    int maxAttempts = 5;
    for (int i = 0; i < maxAttempts; i++) {
      String autogeneratedUsername = StringUtil.generateBaseSuffixUsername(name);
      if (!userRepository.existsByUsername(autogeneratedUsername)) {
        User newUser = new User(email, name, autogeneratedUsername, avatar);
        User savedUser = userRepository.save(newUser);
        assignDefaultRole(savedUser);
        return savedUser;
      }
    }
    throw new RuntimeException(
        "Could not generate a unique username after " + maxAttempts + " attempts");
  }

  private void assignDefaultRole(User user) {
    Role studentRole =
        roleRepository
            .findByName(DEFAULT_ROLE_NAME)
            .orElseThrow(
                () ->
                    new IllegalStateException(
                        "Default role '" + DEFAULT_ROLE_NAME + "' is missing"));

    if (!userRoleRepository.existsByIdUserIdAndIdRoleName(user.getId(), studentRole.getName())) {
      userRoleRepository.save(new UserRole(user, studentRole));
    }
  }

  @Transactional
  public User updateProfileAuthorized(
      String currentUserEmail, Long targetUserId, UpdateUserRequest req) {
    User currentUser =
        userRepository
            .findByEmailWithRoles(currentUserEmail)
            .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "User not found"));

    User targetUser = userRepository.findById(targetUserId).orElse(null);

    boolean isAdmin =
        currentUser.getUserRoles() != null
            && currentUser.getUserRoles().stream()
                .map(UserRole::getRole)
                .anyMatch(
                    role ->
                        RoleConstants.ADMIN.equalsIgnoreCase(role.getName())
                            || (role.getPermissions() != null
                                && (role.getPermissions() & PermissionConstants.ADMIN) != 0L));

    if (targetUser == null || (!currentUser.getId().equals(targetUserId) && !isAdmin)) {
      throw new ResponseStatusException(HttpStatus.NOT_FOUND, "User not found");
    }

    applyUpdates(targetUser, req);
    return userRepository.save(targetUser);
  }

  @Transactional
  public User updateCurrentUserProfile(String email, UpdateUserRequest req) {
    User user =
        userRepository
            .findByEmail(email)
            .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "User not found"));

    applyUpdates(user, req);
    return userRepository.save(user);
  }

  private void applyUpdates(User user, UpdateUserRequest req) {
    if (req.username() != null && !req.username().equals(user.getUsername())) {
      if (userRepository.existsByUsername(req.username())) {
        throw new ResponseStatusException(HttpStatus.CONFLICT, "Username already taken");
      }
      user.setUsername(req.username());
    }
    if (req.displayName() != null) {
      user.setDisplayName(req.displayName());
    }
    if (req.avatarUrl() != null) {
      user.setAvatarUrl(req.avatarUrl());
    }
  }
}
