package com.goctrithuc.backend.services;

import com.goctrithuc.backend.common.util.StringUtil;
import com.goctrithuc.backend.entities.Role;
import com.goctrithuc.backend.entities.User;
import com.goctrithuc.backend.entities.UserProvider;
import com.goctrithuc.backend.entities.UserRole;
import com.goctrithuc.backend.repositories.RoleRepository;
import com.goctrithuc.backend.repositories.UserProviderRepository;
import com.goctrithuc.backend.repositories.UserRepository;
import com.goctrithuc.backend.repositories.UserRoleRepository;
import java.util.Optional;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class UserPersistenceService {

  private static final String DEFAULT_ROLE_NAME = "student";

  private final UserRepository userRepository;
  private final UserProviderRepository userProviderRepository;
  private final RoleRepository roleRepository;
  private final UserRoleRepository userRoleRepository;

  public UserPersistenceService(
      UserRepository userRepository,
      UserProviderRepository userProviderRepository,
      RoleRepository roleRepository,
      UserRoleRepository userRoleRepository) {
    this.userRepository = userRepository;
    this.userProviderRepository = userProviderRepository;
    this.roleRepository = roleRepository;
    this.userRoleRepository = userRoleRepository;
  }

  @Transactional
  public void syncUser(
      String providerName, String providerUserId, String email, String name, String avatar) {
    Optional<UserProvider> existingProvider =
        userProviderRepository.findByProviderNameAndProviderUserId(providerName, providerUserId);

    if (existingProvider.isEmpty()) {
      User user =
          userRepository
              .findByEmail(email)
              .orElseGet(() -> createUserWithUniqueUsername(email, name, avatar));

      UserProvider newProvider = new UserProvider(user, providerName, providerUserId);
      userProviderRepository.save(newProvider);
    }
  }

  private User createUserWithUniqueUsername(String email, String name, String avatar) {
    int maxAttempts = 5;
    for (int i = 0; i < maxAttempts; i++) {
      String autogeneratedUsername = StringUtil.generateBaseSuffixUsername(name);
      if (!userRepository.existsByUsername(autogeneratedUsername)) {
        User newUser = new User(email, name, autogeneratedUsername, avatar);
        User savedUser = userRepository.save(newUser);
        assignDefaultRole(savedUser);
        return savedUser;
      }
    }
    throw new RuntimeException(
        "Could not generate a unique username after " + maxAttempts + " attempts");
  }

  private void assignDefaultRole(User user) {
    Role studentRole =
        roleRepository
            .findByName(DEFAULT_ROLE_NAME)
            .orElseThrow(
                () ->
                    new IllegalStateException(
                        "Default role '" + DEFAULT_ROLE_NAME + "' is missing"));

    if (!userRoleRepository.existsByIdUserIdAndIdRoleName(user.getId(), studentRole.getName())) {
      userRoleRepository.save(new UserRole(user, studentRole));
    }
  }
}
