server:
  port: ${APP_PORT:?APP_PORT is required}

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  config:
    # Tell Spring to import your root .env file
    import: optional:file:../.env[.properties]

  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:?POSTGRES_PORT is required}/goctrithuc
    username: ${POSTGRES_USER:?POSTGRES_USER is required}
    password: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    schemas: public

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID is required} # Get this from Google Cloud Console
            client-secret: ${GOOGLE_CLIENT_SECRET:?GOOGLE_CLIENT_SECRET is required}
            scope: email, profile
          github:
            client-id: ${GITHUB_CLIENT_ID:?GITHUB_CLIENT_ID is required} # Get this from GitHub Developer Settings
            client-secret: ${GITHUB_CLIENT_SECRET:?GITHUB_CLIENT_SECRET is required}
            scope: read:user, user:email


app:
  frontend:
    oauth2-redirect-uri: http://localhost:${FRONTEND_PORT:?FRONTEND_PORT is required}/dashboard
  upload-dir: ${UPLOAD_DIR:?UPLOAD_DIR is required}